NOAA-OWP/wres

- .github/workflows/databaseMigrationChecks.yml
Adding database migration checking to PRs where database files were changed and also upon the creating of the staging release
- 
- Tested in fork https://github.com/epag/wres-copy/actions
- Fixes #30 
> Adding database migration checking

- .github/workflows/commitChecks.yml
We were only running on every commit to master, run every commit no matter the branch
- 
- 
- Fixes #54
> Update WF to run every commit

- .github/workflows/commitChecks.yml
Added in-memory testing to code-check workflow
- 
- 
- Fixes #59 
> Added in-memory testing 

- build.gradle
> Fixing transitive dependency issue

- Dockerfile
- build.gradle
- scripts/localWindowsDeployScripts/broker/Dockerfile
- scripts/localWindowsDeployScripts/eventsbroker/Dockerfile
- scripts/localWindowsDeployScripts/redis/Dockerfile
- scripts/localWindowsDeployScripts/tasker/Dockerfile
- scripts/localWindowsDeployScripts/vis/Dockerfile
- scripts/localWindowsDeployScripts/wres/Dockerfile
- wres-broker/Dockerfile
- wres-eventsbroker/Dockerfile
- wres-redis/Dockerfile
- wres-tasker/Dockerfile
- wres-vis/Dockerfile
- wres-writing/Dockerfile
> fixes #67 Dependency and dockerfile upgrades for deployment

- build.gradle
> fixes #67 Fixed dependency upgrades

- compose-entry.yml
- compose-workers.yml
> Deployment 6.25 yml files

- compose-entry.template.yml
- compose-workers.template.yml
forgot to add the registry we push these images to, quick follow up
- 
- 
> Adding registry to compose

- .github/workflows/commitChecks.yml
- wres-reading/test/wres/reading/wrds/nwm/WrdsNwmReaderTest.java
In order to more throughly test code add a full build to the action testing
- 
- 
- Fixes #309 
> Adding build command to commit check action

- wres-eventsbroker/nonsrc/cert-users.properties
Issue introduced logging into artemis console with new cert process. Quick Fix 
- 
- 
> updating order to align with new cert workflow

- build.gradle
- wres-broker/Dockerfile
- wres-eventsbroker/Dockerfile
Dependency updates for 6.26; see #313
- Dependency updates.
- 
- Fixes #313
> GitHub 313

- compose-entry.template.yml
- compose-workers.template.yml
> Adding auto restart to nginx and cadvisor

- .github/workflows/commitChecks.yml
- .github/workflows/databaseMigrationChecks.yml
- .github/workflows/dockerRelease.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
increaseing fetch depth of automations so artifacts done share the commit ID of the most recent commit but rather the commit of when they were last updated 
- 
- 
- Fixes #345
> Increasing fetch depth of automations

- README.md
> Update README.md to include license and terms

- LICENSE
> Update LICENSE per guidance from OWP PMO

- build.gradle
- scripts/dockerize.sh
- wres-eventsbroker/Dockerfile
> Updating artemis

- wres-vis/src/wres/vis/charts/ChartFactory.java
> setting timezone for JFreeChart

- compose-entry.yml
- compose-workers.yml
> Docker compose files used for 6.28.

- wres-tasker/src/wres/tasker/Tasker.java
> Fixing vulnerabilities; refs GitHub #392

- Dockerfile
- wres-eventsbroker/Dockerfile
- wres-tasker/Dockerfile
- wres-vis/Dockerfile
- wres-writing/Dockerfile
> Updated Dockerfiles for openjdk and unzip; refs GitHub #392

- wres-tasker/dist/lib/static/html/index.html
- wres-tasker/src/wres/tasker/Tasker.java
> Removed unsafe options from content security policy; refs Github #392

- build.gradle
- wres-redis/Dockerfile
Update dependencies
- 
- 
- Fixes #403
> 6.29 dependency update

- compose-entry.yml
- compose-workers.yml
> automated deploy compose changes

- wres-datamodel/src/wres/datamodel/time/TimeSeriesStore.java
> Filter by feature when retrieving time-series datasets in memory, #408.

- src/wres/pipeline/pooling/PoolSupplier.java
- wres-datamodel/src/wres/datamodel/time/TimeWindowSlicer.java
- wres-vis/src/wres/vis/data/ChartDataFactory.java
> Omit resampled quantiles when plotting duration diagrams, #399.

- README.md
> Updated README.md to be a bit more developer focused; refs #439, #365

- compose-entry.yml
- compose-workers.yml
> Docker files for v6.30; refs GitHub #448

- compose-entry.yml
> Changed to use default net, not different net; refs GitHub #448

- build.gradle
Downgrade postgresql and liquibase to address a performance impact until a more permanent solution is found
- 
- 
- Fixes 450
> Downgrading postgresql and liquibase for performance

- build.gradle
Adding CSV output for Jacoco test coverage report so that we can generate badges.
- build.gradle only; no code
- Make sure tests pass.
- #419
> Adding CSV output for test coverage report; refs GitHub #419

- .github/workflows/commitChecks.yml
Add tooling in commitChecks.yml to produce a Jacoco report in an Action and post a comment to the PR.
- 
- 
- Fixes #419
> Updated to include Jacoco reports in action and PR; #419

- Dockerfile
- Poderfile
- build.gradle
- scripts/localWindowsDeployScripts/eventsbroker/Dockerfile
- wres-eventsbroker/Dockerfile
- wres-eventsbroker/Poderfile
- wres-vis/Dockerfile
- wres-vis/Poderfile
- wres-writing/Dockerfile
- wres-writing/Poderfile
update dependencies
- 
- 
- Fixes #463
> Dependency update

- compose-entry.yml
- compose-workers.yml
- podman-compose-entry.yml
- podman-compose-workers.yml
> Updating compose files

- wres-tasker/src/wres/tasker/WresJob.java
Added rows and cols to validated text area; refs #407
- 
- 
> Added rows and cols to validated text area; refs #407

- .gitignore
> Adding jenkins job file to ignore list

- scripts/poderize.sh
> poderize fix

- scripts/poderize.sh
> poderize fixes

- build.gradle
> Upping net.minidev:json-smart to 2.5.2; refs #478

- build.gradle
> Excluded minidev from jayway; refs #478

- build.gradle
Final push of reorganized and commented mock-server testImplementation.
- 
- 
> Final push - Cleaned up and comments mock-server implementation; refs #478

- Dockerfile
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- wres-eventsbroker/Dockerfile
- wres-tasker/Dockerfile
- wres-vis/Dockerfile
- wres-writing/Dockerfile
> Updated dependencies; refs #510

- podman-compose-entry.yml
- podman-compose-workers.yml
> YAML files for 6.32 deployment; refs #509

- build.gradle
> Forgot to remove key

- Dockerfile
- wres-eventsbroker/Dockerfile
- wres-redis/Dockerfile
- wres-tasker/Dockerfile
- wres-vis/Dockerfile
- wres-writing/Dockerfile
> Dockerfile updates for 6.33; refs #565

- podman-compose-entry.yml
- podman-compose-workers.yml
> Github565 yml

- build.gradle
si-units update.
- 
- 
- Fixes #515.
> Update the si-units dep, #515.

- build.gradle
Update junit jupiter.
- 
- 
- Fixes #516.
> Update junit jupiter and declare the platform launcher explicitly, #516.

- src/wres/pipeline/EvaluationUtilities.java
- wres-config/src/wres/config/yaml/DeclarationInterpolator.java
- wres-config/test/wres/config/yaml/DeclarationInterpolatorTest.java
> Generate summary statistics across features, by default, #617.

- wres-reading/src/wres/reading/wrds/nwm/DateTimeDeserializer.java
- wres-reading/test/wres/reading/wrds/nwm/WrdsNwmJsonReaderTest.java
- wres-reading/test/wres/reading/wrds/nwm/WrdsNwmReaderTest.java
> Fixing WRDS datetime formatter to support ISO default formats

- podman-compose-entry.yml
- podman-compose-workers.yml
> Updated compose files for 7.1 deploy

- wres-external-services-tests/dist/src/test/java/wres/testing/WrdsNwmTest.java
> Updating external wrds test with new URL path
